"""
VTK Deserialization module for decoding payloads back into VTK memory objects.

This module parses the custom `<FILE NAME=...>` XML wrappers generated by `vtk_serializer.py` 
and extracts the raw VTK XML payloads. It then feeds them back into standard VTK readers 
(`vtkXMLUnstructuredGridReader`, etc.) instantiated in memory to reconstruct the datasets 
for ParaView pipeline execution.
"""

import vtk
import re

def deserialize_vtk_from_buffer(buffer_bytes):
    """
    Parses a DPvzVtkData buffer containing multiple `<FILE NAME='...'>` blocks and 
    optional hierarchy metadata (`<FILE NAME='hierarchy.json'>`).
    
    Args:
        buffer_bytes (bytes): The raw payload extracted from the DPvz archive.
        
    Returns:
        list of dict: Each dictionary contains 'index' (int), 'name' (str), and 'dataset' (vtkDataSet or None).
    """
    import json
    text = buffer_bytes.decode('utf-8', errors='ignore')
    
    pattern = r"<FILE NAME='([^']+)'>\n(.*?)\n</FILE NAME='\1'>\n"
    matches = dict(re.findall(pattern, text, re.DOTALL))
    
    results = []
    
    if 'hierarchy.json' in matches:
        try:
            meta = json.loads(matches['hierarchy.json'])
            for blk in meta.get("blocks", []):
                idx = blk.get("index", 0)
                name = blk.get("name", f"block_{idx}")
                filename = blk.get("filename")
                ds = None
                if filename and filename in matches:
                    data = matches[filename]
                    if filename.endswith(".vtu"):
                        reader = vtk.vtkXMLUnstructuredGridReader()
                    elif filename.endswith(".vtp"):
                        reader = vtk.vtkXMLPolyDataReader()
                    else:
                        reader = vtk.vtkXMLGenericDataObjectReader()
                    reader.SetReadFromInputString(1)
                    reader.SetInputString(data)
                    reader.Update()
                    ds = reader.GetOutput()
                results.append({"type": "block", "index": idx, "name": name, "dataset": ds})
                
            if "data_assembly_xml" in meta:
                results.append({"type": "assembly", "index": -1, "name": "__assembly__", "dataset": None, "xml": meta["data_assembly_xml"]})
                
            return results
        except Exception:
            pass
            
    # Legacy fallback for archives without hierarchy.json
    idx = 0
    for filename, data in matches.items():
        if filename == 'hierarchy.json':
            continue
        if filename.endswith(".vtu"):
            reader = vtk.vtkXMLUnstructuredGridReader()
        elif filename.endswith(".vtp"):
            reader = vtk.vtkXMLPolyDataReader()
        else:
            reader = vtk.vtkXMLGenericDataObjectReader()
        reader.SetReadFromInputString(1)
        reader.SetInputString(data)
        reader.Update()
        ds = reader.GetOutput()
        if ds:
            results.append({"type": "block", "index": 0, "name": "block_0", "dataset": ds})
            idx += 1
            
    return results


def populate_pdc_from_buffer(pdc, buffer_bytes, part_counters):
    """
    Parses a buffer and populates a vtkPartitionedDataSetCollection while maintaining
    the correct block names and partition indices across multiple writing ranks.
    
    Args:
        pdc (vtkPartitionedDataSetCollection): Target collection to populate.
        buffer_bytes (bytes): Raw payload from archive.get_data().
        part_counters (dict): Map tracking current partition index per block index.
        
    Returns:
        list of dict: The parsed items returned by deserialize_vtk_from_buffer.
    """
    items = deserialize_vtk_from_buffer(buffer_bytes)
    for item in items:
        if item.get("type") == "assembly":
            # Only initialize and set the assembly if we haven't already 
            # (since every rank might stream the identical assembly)
            if not pdc.GetDataAssembly():
                asm = vtk.vtkDataAssembly()
                asm.InitializeFromXML(item["xml"])
                pdc.SetDataAssembly(asm)
            continue
            
        # Standard block item processing
        idx = item.get("index", 0)
        name = item.get("name", "")
        ds = item.get("dataset", None)
        
        while pdc.GetNumberOfPartitionedDataSets() <= idx:
            pdc.SetNumberOfPartitionedDataSets(idx + 1)
        if name:
            meta = pdc.GetMetaData(idx)
            if meta:
                meta.Set(vtk.vtkCompositeDataSet.NAME(), name)
        if ds is not None:
            p_idx = part_counters.get(idx, 0)
            pdc.SetPartition(idx, p_idx, ds)
            part_counters[idx] = p_idx + 1
            
    return items
